added db  support

diff --git a/src/fakeroot/opt/45drives/tools/findosd b/src/fakeroot/opt/45drives/tools/findosd
--- a/src/fakeroot/opt/45drives/tools/findosd
+++ b/src/fakeroot/opt/45drives/tools/findosd
@@ -1,5 +1,7 @@
 #!/bin/bash
 # findosd <osd.id>
+# Brett Kelly 2021
+# 45Drives
 # MUST BE RUN FROM OSD HOST WHERE OSD IS LOCATED
 # IF OSD HOST IS NOT THIS HOST EXIT
 
@@ -19,22 +21,12 @@ debug(){
 	echo NAME:$NAME
 	echo OSD_FSID:$OSD_FSID
 	echo OSD_HOST:$OSD_HOST
-	echo OSD_BLOCK_VOLID:$OSD_BLOCK_VOLID
-	echo OSD_DB_VOLID:$OSD_DB_VOLID
+	echo OSD_JSON:$OSD_JSON
+	echo OSD_BLOCK_DEVID:$OSD_BLOCK_DEVID
+	echo OSD_BLOCK_LVMID:$OSD_BLOCK_LVMID
+	echo OSD_DB_DEVID:$OSD_DB_DEVID
+	echo OSD_DB_LVMID:$OSD_DB_LVMID
 }
-getblockvolid(){
-	local OSD_FSID=$1
-	local OSD_VOLID_JSON=$(ceph-volume lvm list --format json)
-	local OSD_VOLID=$(echo $OSD_VOLID_JSON | jq -r --arg type "$TYPE" '.[] | .[] | select(.tags["ceph.type"]=="block") | .tags["ceph.type"] + ":" + .tags["ceph.osd_fsid"] + ":" + .vg_name' | grep $OSD_FSID | cut -d : -f 3)
-	echo "$OSD_VOLID"
-}
-getdbvolid(){
-	local OSD_FSID=$1
-	local OSD_VOLID_JSON=$(ceph-volume lvm list --format json)
-	local OSD_VOLID=$(echo $OSD_VOLID_JSON | jq -r --arg type "$TYPE" '.[] | .[] | select(.tags["ceph.type"]=="db") | .tags["ceph.type"] + ":" + .tags["ceph.osd_fsid"] + ":" + .vg_name' | grep $OSD_FSID | cut -d : -f 3)
-	echo "$OSD_VOLID"
-}
-
 ## INPUTS
 
 DEVICE_PATH=/dev/disk/by/vdev
@@ -85,7 +77,7 @@ fi
 
 ## MAIN
 
-OSD_FSID=$(ceph osd find $OSD_ID 2>/dev/null | jq -r '.osd_fsid')
+# Find which host the OSD belongs to
 OSD_HOST=$(ceph osd find $OSD_ID 2>/dev/null | jq -r '.host')
 if [ "$OSD_HOST" == "null" ];then
 	OSD_HOST=$(ceph osd find $OSD_ID | jq -r '.crush_location.host')
@@ -96,36 +88,66 @@ else
 	fi
 fi
 
-# Get Volume Group ID's
-if [ "$TYPE" == "block" ];then
-	OSD_BLOCK_VOLID="$(getblockvolid $OSD_FSID)"
-	OSD_BLOCK_DEVID=$(pvs --noheadings -o pv_name,vg_name | grep $OSD_BLOCK_VOLID | awk '{print $1}')
-elif [ "$TYPE" == "db" ];then
-	OSD_DB_VOLID="$(getdbvolid $OSD_FSID)"
-	OSD_DB_VOLID="$(pvs --noheadings -o pv_name,vg_name | grep $OSD_DB_VOLID | awk '{print $1}')"
-elif [ "$TYPE" == "both" ];then
-	OSD_BLOCK_VOLID="$(getblockvolid $OSD_FSID)"
-	OSD_DB_VOLID="$(getdbvolid $OSD_FSID)"
-	OSD_BLOCK_DEVID=$(pvs --noheadings -o pv_name,vg_name | grep $OSD_BLOCK_VOLID | awk '{print $1}')
-	OSD_DB_VOLID="$(pvs --noheadings -o pv_name,vg_name | grep $OSD_DB_VOLID | awk '{print $1}')"
+# Get ceph-volume lvm info for osd.id
+OSD_JSON=$(ceph-volume lvm list --format json | jq -r --arg id "$OSD_ID" '.[] | .[] | select(.tags["ceph.osd_id"]==$id)')
+if [ -z "$OSD_JSON" ]; then
+	echo "Can't find osd.$OSD_ID on this host"
+	exit 1
 fi
 
+#Get devices from osd_ceph json
+if [ "$TYPE" == "block" ];then
+	OSD_BLOCK_DEVID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="block") | .devices | .[]')"
+	OSD_BLOCK_LVMID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="block") | .lv_path')"
+elif [ "$TYPE" == "db" ];then
+	OSD_DB_DEVID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="db") | .devices | .[]')"
+	OSD_DB_LVMID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="db") | .lv_path')"
+elif [ "$TYPE" == "both" ];then
+	OSD_BLOCK_DEVID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="block") | .devices | .[]')"
+	OSD_BLOCK_LVMID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="block") | .lv_path')"
+	OSD_DB_DEVID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="db") | .devices | .[]')"
+	OSD_DB_LVMID="$(echo $OSD_JSON | jq -r 'select(.tags["ceph.type"]=="db") | .lv_path')"
+fi
 
-# IFS=$'\n' 
-# j=0
-# for i in $(cat $CONFIG_PATH/vdev_id.conf); do
-# 	bay=$(echo $i | grep alias | awk '{print $2}')
-# 	if [ ! -z "$bay" ];then 
-# 		BAY[$j]=$bay
-# 	fi
-# 	let j=j+1
-# done
-# for i in "${BAY[@]}";do
-# 	#echo "$(readlink -f /dev/$i) $OSD_DEVID "
-# 	if [ "$(readlink -f /dev/$i)" == "$OSD_DEVID" ];then
-# 		echo $i
-# 	fi
-# done
+# Display device names
+if [ $NAME == "device" ];then
+	IFS=$'\n' 
+	j=0
+	for i in $(cat $CONFIG_PATH/vdev_id.conf); do
+		bay=$(echo $i | grep alias | awk '{print $2}')
+		if [ ! -z "$bay" ];then 
+			BAY[$j]=$bay
+		fi
+		let j=j+1
+	done
+	if [ ! -z $OSD_BLOCK_DEVID ];then
+		for i in "${BAY[@]}";do
+			if [ "/dev/$i" == "$OSD_BLOCK_DEVID" ] || [ "/dev/disk/by-vdev/$i" == "$OSD_BLOCK_DEVID" ] ;then
+				echo "block=$OSD_BLOCK_DEVID"
+			elif [ "$(readlink -f /dev/$i)" == "$OSD_BLOCK_DEVID" ];then
+				echo "block=/dev/$i"
+			fi
+		done
+	fi
+	if [ ! -z $OSD_DB_DEVID ];then
+		for i in "${BAY[@]}";do
+			if [ "/dev/$i" == "$OSD_DB_DEVID" ] || [ "/dev/disk/by-vdev/$i" == "$OSD_DB_DEVID" ] ;then
+				echo "block.db=$OSD_DB_DEVID"
+			elif [ "$(readlink -f /dev/$i)" == "$OSD_DB_DEVID" ];then
+				echo "block.db=/dev/$i"
+			fi
+		done
+	fi
+fi
+
+if [ $NAME == "lvm" ];then
+	if [ ! -z $OSD_BLOCK_LVMID ];then
+		echo "block=$OSD_BLOCK_LVMID"
+	fi
+	if [ ! -z $OSD_DB_LVMID ];then
+		echo "block.db=$OSD_DB_LVMID"
+	fi
+fi
 
 if [ $DEBUG_FLAG -eq 1 ];then
 	debug
